### ISSUE TITLE
Feature request: switch to Leaflet 

### ISSUE THREAD

**Issue by araichev** [falling-fruit/falling-fruit#11]
Nice app!
I have a feature request: switch to Leaflet JS for your map engine.
Leaflet is an excellent library and also open-source, so it better jives with your ethos.

**Comment by ezwelty** [comment]
@araichev Point taken. Unfortunately, for the time being, we don't have the bandwidth to rewrite all of the code to use different services for the maps, geocoding, and street view features. (We also get a grant from Google each year so that our large use of these services is free). Anything that major will have to wait until the future planned rewrite of the website. However, I did just add the standard OpenStreetMap layer to the map views, as a small start.

**Comment by dbalatero** [comment]
@ezwelty should we mark this closed?
