### ISSUE TITLE
locations* API issues

### ISSUE THREAD

**Issue by dbalatero** [falling-fruit/falling-fruit#17]
Return both `type_ids` and `type_names`. `type_names` are just common names (in the specified locale), and lack scientific name. Can either discard `type_names` and use `type_ids` to build all needed strings from `types.json`, or if this is too slow for the list view, generate a locale-specific location "title" server-side, as was previously available from the Rails API.

**Comment by dbalatero** [comment]
@ezwelty I think I might just generate a specific title server-side to mirror the Rails API?

**Comment by ezwelty** [comment]
@dbalatero Mirroring the behavior of the Rails API sounds good. However, this means localization logic in the NodeJS API, due to the term "Others" for 3+ types. To make it as universal as possible without locale logic for now, how about this behavior:

**one type**
old: "Common name"
new: "Common name"

**two types**
old: "Common name & Common name"
new: "Common name & Common name" -or- "Common name, Common name"

**three+ types**
old: "Common name & Others"
new: "Common name (+ length-1)" -or- "Common name, Common name, ..."

**Comment by dbalatero** [comment]
Hmm, now that I updated types to have locale logic in that one place, I almost want to revert adding the `title` to the API request in #22 and just do the client-side thing all around/

**Comment by ezwelty** [comment]
@dbalatero That makes sense. I just made a commit for list joining type_names with ", " and letting the css add the overflow ellipsis (
https://github.com/falling-fruit/falling-fruit-mobile/commit/401f04acb084c4ed1b5e58eeb958194a72924495).

We definitely don't need type_names and title in locations/id.json, since we generate everything from type_ids. But for the list (locations.json), I guess it comes down to client-side performance. If it's not too slow to use type_ids to generate the names we need for the list client-side (or type_names to generate the list), that's all we need there too.

**Comment by dbalatero** [comment]
> If it's not too slow to use type_ids to generate the names we need for the list client-side (or type_names to generate the list), that's all we need there too.

I wouldn't imagine it's too slow!
