### ISSUE TITLE
ChangesController.index has inefficient query

### ISSUE THREAD

**Issue by lelelelemon** [falling-fruit/falling-fruit#29]
r = ActiveRecord::Base.connection.execute("SELECT string_agg(COALESCE(#{i18n_name_field}t.name),', ') as type_title,
     extract(days from (NOW()-c.created_at)) as days_ago, c.location_id, c.user_id, c.description, c.remote_ip, l.city, l.state, l.country
     FROM changes c, locations l, types t
     WHERE t.id=ANY(l.type_ids) AND l.id=c.location_id AND NOT c.spam
     GROUP BY l.id, c.location_id, c.user_id, c.description, c.remote_ip, c.created_at ORDER BY c.created_at DESC LIMIT 100");

Here, join these 3 tables together is quite time-consuming, because of the join on any condition for types and locations, a better solution is to separate it into 2 queries:
    changes_query = ActiveRecord::Base.connection.execute("SELECT 1 as type_title,
      extract(days from (NOW()-c.created_at)) as days_ago, c.location_id, c.user_id, c.description, c.remote_ip, l.city, l.state, l.country
      FROM changes c, locations l
      WHERE l.id=c.location_id
      GROUP BY l.id, c.location_id, c.user_id, c.description, c.remote_ip, c.created_at, c.author ORDER BY c.created_at DESC LIMIT 100")
    
    @changes = changes_query.collect{ |row| row }
    lids = @changes.collect{|c| c['location_id']}.uniq.compact.join(",")
    titles_query = ActiveRecord::Base.connection.execute("SELECT string_agg(COALESCE(#{i18n_name_field}t.name),', ') as type_title, l.id
      FROM locations l, types t
      WHERE t.id=ANY(l.type_ids) and l.id IN (#{lids}) GROUP BY l.id  ")
    @titles = titles_query.collect{ |row| {row['id'] => row['type_title']} }.reduce Hash.new, :merge 
    
    @changes.each do |c|
      c['type_title'] = @titles[c['location_id']]
    end

**Comment by ezwelty** [comment]
@lelelelemon Thanks for the suggestion. I ran some tests, and while your suggested method is slightly faster (by 0.09 s, or 20%) for 100 items (`LIMIT 100`), it scales very poorly due to the injection of `lids` into the query for `titles_query`. It begins to be slower that the original method around 1000 items, and by 5000 items it is *6 s* slower. For that reason, I think I'd prefer to keep the original logic, since we may change the limit in the future.

@somerandomsequence Thoughts?
